# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeRecode',
            new_name='LikeRecord',
        ),
    ]
