# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180716_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='relly_to',
            new_name='reply_to',
        ),
    ]
